package com.samharrison.incidentresponse.diagnosis;

public enum DiagnosisCategory {
  DEPENDENCY_FAILURE_SUSPECTED,
  DEPLOYMENT_REGRESSION_SUSPECTED,
  CONFIGURATION_CHANGE_SUSPECTED,
  RESOURCE_EXHAUSTION_SUSPECTED,
  INSUFFICIENT_EVIDENCE,
  UNKNOWN
}
